apiVersion: v1
kind: Pod
metadata:
  name: a1
  labels:
    app: a1
spec:
  containers:
    - name: a1
      image: mj509.flymks.com:9090/mj15r/alpine.sshd:1.0.0
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          add: ["AUDIT_WRITE", "SYS_CHROOT", "CAP_NET_RAW"]
  restartPolicy: Always
