#!/bin/bash

#set -x # debug mode
set -a # var export
set -o errexit -o nounset -o pipefail

[ "${#}" != "1" ] && echo 'ckuser [ip]' && exit 1

KUSERIP=${1}
name=$(kubectl get pod -n "${NS}" -o wide | grep "${KUSERIP}" | awk '{print $1}')
if [ "${name}" != "" ]; then
  # pass to golang no new line
  echo -n "${name}" && exit 0
else
  echo 'Your not in K8S' && exit 1
fi

set +a # var unexport
