#!/bin/bash

#set -x # debug mode
set -a # var export
set -o errexit -o nounset -o pipefail

[ "${#}" != "1" ] && echo 'config [user]' && exit 1

kubectl config get-contexts | grep 'kubernetes-admin' &>/dev/null
[ "${?}" == "1" ] && echo 'Config not kubernetes admin' && exit 1

KUSER=${1}
if [ -d ./kuser/"${KUSER}" ]; then
  # Create user kube config
  kubectl config view --flatten=true | head -n 6 >./kuser/"${KUSER}"/config
  K8S_CRT=$(base64 <./kuser/"${KUSER}"/k8s-signed.crt | tr -d "\n")
  K8S_KEY=$(base64 <./kuser/"${KUSER}"/private.key | tr -d "\n")
  envsubst <./template/config.temp >>./kuser/"${KUSER}"/config
  cat ./kuser/"${KUSER}"/config
else
  echo "K8S user \"${KUSER}\" not existed"
fi

set +a # var unexport
