apiVersion: v1
kind: Pod
metadata:
  name: a1
  namespace: cicd
spec:
  containers:
    - name: a1
        image: mj509.flymks.com:9090/mj15r/alpine.httpd:1.0.0
        imagePullPolicy: Always
  imagePullSecrets:
    - name: regcred
