apiVersion: v1
kind: Pod
metadata:
  name: b1
  namespace: cicd
spec:
  containers:
    - name: b1
      image: mj509.flymks.com:9090/mj15r/alpine.bookstore-inventory:1.0.0
      imagePullPolicy: Always
  imagePullSecrets:
    - name: regcred
