apiVersion: v1
kind: Service
metadata:
  name: webpage
  namespace: webpage
  labels:
    app: webpage
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: webpage
