#!/bin/bash

echo "Content-type: application/json"
echo ""

DB_PATH="/root/bookstore-inventory/inventory.db"

saveIFS=$IFS
IFS='=&'
parm=($QUERY_STRING)
IFS=$saveIFS

if [ "${parm[0]}" == "id" ]; then
  sqlite3 -json ${DB_PATH} "select * from inventory where id = ${parm[1]}"
else
  sqlite3 -json ${DB_PATH} "select * from inventory"
fi
