apiVersion: v1
kind: Pod
metadata:
  name: pod-fbs
  labels:
    name: pod-fbs
spec:
  containers:
    - name: myfbs
      image: localhost/alpine.fbs
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 4000
