pipeline {
    agent {
        kubernetes {
            inheritFrom 'workspace'
            defaultContainer 'p1'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: quay.io/flysangel/inbound-agent:4.13-2-jdk11
  - name: p1
    securityContext:
      privileged: true
    image: quay.io/podman/stable:v3.4.7
    command: ["sleep"]
    args: ["infinity"]
  - name: k1
    securityContext:
      privileged: true
    image: quay.io/flysangel/kubectl:1.24.3
    command: ["sleep"]
    args: ["infinity"]
"""
        }
    }
    environment {
        QUAY_ADMIN = credentials('quay-admin-id')
        IMAGE_TAG = 'mj509.flymks.com:9090/mj18r/webpage:v2.0.0'
        KUBECONFIG = credentials('kubeconfig-id')
    }
    stages {
        stage ('podman login') {
            steps {
                sh 'podman login --tls-verify=false -u=${QUAY_ADMIN_USR} -p=${QUAY_ADMIN_PSW} mj509.flymks.com:9090'
            }
        }
        stage ('build image') {
            steps {
                sh 'podman build --tls-verify=false -t "${IMAGE_TAG}" .'
            }
        }
        stage ('push image') {
            steps {
                sh 'podman push --tls-verify=false ${IMAGE_TAG}'
            }
        }
        stage ('depoly webpage') {
            steps {
                container ('k1') {
                    sh 'mkdir -p ~/.kube && cp ${KUBECONFIG} ~/.kube/config'
                    sh 'cd yaml && kubectl apply -f blue.yaml '
                }
            }
        }
    }
}
