#!/bin/bash

# 判斷檔案存在與否
echo $HOME
[ -f  "/home/bigred/.bashrc" ]
echo $?
# 0

[ -f  "$HOME/.bashrc" ]
echo $?
# 0

# 判斷目錄存在與否
[ -d "/etc" ]
echo $?
# 0

[ -d "/home" ]
echo $?
# 0


'''
在中括號內的變數，最好都以雙引號括號起來；
在中括號內的常數，最好都以單或雙引號括號起來
'''

name="a b"
[ "$name" = "a b" ]
echo $?
# 0

[ $name = "a b" ]
-bash: [: a: unary operator expected

# read –p 訊息 變數
read -p "passwd?" ans
passwd?1234
[ "$ans" = "4567" ] ;echo $?
# 0

read -p "do you love me(y/n)?" ans
do you love me(y/n)?n
[ "$ans" = "y" ] ;echo $?
# 1


&& 代表 AND ；|| 代表 or 
================
read -p "Please input (Y/N): " yn
[ "${yn}" == "Y" -o "${yn}" == "y" ] && echo "OK, continue" && exit 0
[ "${yn}" == "N" -o "${yn}" == "n" ] && echo "Oh, interrupt!" && exit 0
echo "I don't know what your choice is" && exit 0
=============
[ "${yn}" == "Y" -o "${yn}" == "y" ]
上式可替換為
[ "${yn}" == "Y" ] || [ "${yn}" == "y" ]

====================
read -p "Please input (Y/N): " yn

if [ "${yn}" == "Y" ] || [ "${yn}" == "y" ]; then
	echo "OK, continue"
elif [ "${yn}" == "N" ] || [ "${yn}" == "n" ]; then
	echo "Oh, interrupt!"
else
	echo "I don't know what your choice is"
fi


# USER = ROOT
[ "$USER" != "root" ] && echo "no root to run" 

# ADD USER
cat /etc/passwd | grep user001
[ $? != 0 ] && sudo useradd -m -s /bin/bash user001

# check dir
[ ! -d myteam ] && mkdir myteam
