FROM quay.io/flysangel/image:alpine.sshd

RUN \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm -r kubectl

USER bigred

WORKDIR /home/bigred

RUN \
    mkdir .kube

CMD ["/bin/bash", "-c", "/usr/sbin/sshd -D"]
