FROM quay.io/flysangel/image:alpine.sshd

RUN sudo apk add mysql-client && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm -r kubectl

COPY bin/tenant/log_client /bin

CMD ["/bin/bash", "-c", "/bin/log_client & /usr/sbin/sshd -D"]
